[package]
name = "rust-msc"
version = "0.1.0"
edition = "2018"

[lib]
name = "pika_binder"
crate-type = ["staticlib"]
path = "src/bind_lib.rs"

[dependencies]
libc = "0.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
