[package]
name = "rust-msc"
version = "0.1.0"
edition = "2018"

[lib]
name = "pikabinder"
crate-type = ["staticlib"]
path = "src/lib.rs"

[dependencies]
libc = "0.2"
serde_json = "1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
